export const languageConst={
    en:{
        "changeProfile":"Change Profile",
        "age": "Age",
      "bloodGroup": "Blood Group",
      "city": "City",
      "donationDate": "Donation Date",
      "gender": "Gender",
      "hemoglobin": "hemoglobin",
      "illness": "illness",
      "mobileNo": "Mobile No",
      "Name": "Name",
      "state": "state",
      "donate" : "Donate Blood",
      "submit" : "Submit",
      "select gender" : "Select gender",
      "select bloodgroup" : "Select Blood Group",
      "close" : "CLOSE",
      "calendar" : "Calendar",
      "save" : "SAVE",
      "bloodRequireData" : "Blood Require Date",
      "location" : "Location",
      "units" : "Units",
      "fatherHusband" : "Father/Husband",
      "male" : "Male",
      "female" : "Female",
      "requestBlood" : "Request Blood"
    },
    hi:{
        "Change Profile":"उदाहरण और वाक्य",
        "age": "आयु",
      "bloodGroup": "ब्लड ग्रुप",
      "city": "शहर",
      "donationDate": "दान दिनांक",
      "gender": "लिंग",
      "hemoglobin": "हीमोग्लोबिन",
      "illness": "बीमारी",
      "mobileNo": "मोबाइल नंबर",
      "Name": "नाम",
      "state": "राज्य",
      "donate" : "रक्तदान करें",
      "submit" : "जमा करें",
      "select gender" : "लिंग चुनें",
      "select bloodgroup" : "रक्त समूह चुनें",
      "close" : "बंद करें",
      "calendar" : "पंचांग",
      "save" : "जमा करें",
      "bloodRequireData" : "रक्त आवश्यक डेटा",
      "location" : "स्थान",
      "units" : "इकाइयाँ",
      "fatherHusband" : "पिता/पति",
      "male" : "पुरुष",
      "female" : "महिला",
      "requestBlood" : "रक्त का अनुरोध करें"
    }
}
