export const languageConst={
    en:{
        "changeProfile":"Change Profile",
        "age": "Age",
      "bloodGroup": "Blood Group",
      "city": "City",
      "donationDate": "Donation Date",
      "gender": "Gender",
      "hemoglobin": "hemoglobin",
      "illness": "illness",
      "mobileNo": "Mobile No",
      "Name": "Name",
      "state": "State",
      "donate" : "Donate Blood",
      "submit" : "Submit",
      "select gender" : "Select gender",
      "select bloodgroup" : "Select Blood Group",
      "close" : "CLOSE",
      "calendar" : "Calendar",
      "save" : "SAVE",
      "District": "District",
      "Tahsil": "Tahsil",
      "Village": "Village",
      "bloodgroup":"Blood Group",
      "DOB":"Date of Birth",
      "anyIllness":"Do you have any type of illness",
      "line1":"  I agree to the",
      "line2":"Terms and Condition",
      "line3":"of Donation",
      "acceptContinue":"Accept & Continue",
      "selectUnits":"Select Units",
      "seleteBloodType":"Select Blood Type",
      "hospitalName":"Hospital Name",
      "RequireDate":"Blood Require Date",
      "bloodDonation":"Blood Donations",
      "bloodRequest":"Blood Requests",
      "home":"Home",
      "donateBlood":"Donate Blood",
      "requestBlood":"Request Blood",
      "bloodDonationHistory":"Blood Donation History",
      "latest" : "Latest",
      "history" : "History",
      "myList":"My List",
      "active":"Active",
      "adminHistory":"History Admin",
      "applyFilter":'Apply Filter',
      "cancel":"Cancel",
      "confirm": "Confirm",
      "clear":"Clear",
      "enterHospitalName":"Enter Hospital Name Here",
      "bloodBankName" : "Blood Bank Name",
      "enterBloodBankName":"Enter Blood Bank Name Here",
      "logout":"Logout",
      "profile":"Profile",
      "changeLanguage":"Change Language",
      "changePassword":"Change Password",
      "about":"About",
      "LOGOUT": "Logout",
      "ARE_YOU_SURE_TO_LOGOUT": "Are you sure to logout?",
      "CANCEL": "Cancel",
      "OK": "OK",
      "fullName" : "Full Name",
      "email" :"Email",
      "pincode":"Pincode",
      "edit":"Edit",
      "editProfile":"Edit-Profile",
      "firstName":"First Name",
      "lastName":"Last Name",
      "update":"Update",
      "details":"Details",
      "bloodBankDetails":"Blood Bank Details",
      "personalDetails":"Personal Details",
      "uploadImageWhileDonating":"Upload Image While Donating",
      "cancelRequest" :" Cancel Request",
      "location":"Location",
      "accept":"Accept",
      "done":"Done",
      "allocate":"Allocate",
      "Re-Allocate":"Re-Allocate",
      "beneficiary":"Beneficiary",
      "Father/Husband":"Father/Husband",
      "units":"Units",
      "donor":"Donor"






      


    },
    hi:{
        "Change Profile":"उदाहरण और वाक्य",
        "age": "आयु",
      "bloodGroup": "ब्लड ग्रुप",
      "city": "शहर",
      "donationDate": "दान दिनांक",
      "gender": "लिंग",
      "hemoglobin": "हीमोग्लोबिन",
      "illness": "बीमारी",
      "mobileNo": "मोबाइल नंबर",
      "Name": "नाम",
      "state": "राज्य",
      "donate" : "रक्तदान करें",
      "submit" : "जमा करें",
      "select gender" : "लिंग चुनें",
      "select bloodgroup" : "रक्त समूह चुनें",
      "close" : "बंद करें",
      "calendar" : "पंचांग",
      "save" : "जमा करें",
      "District": "ज़िला",
      "Tahsil": "तहसील",
      "Village": "गाँव",
      "anyIllness":"क्या आपको किसी प्रकार की बीमारी है",
      "line1":"मैं दान के ",
      "line2":"नियमों और शर्तों",
      "line3":"से सहमत हूं",
      "acceptContinue":"स्वीकार करें और जारी रखें",
      "selectUnits":"इकाइयों का चयन करें",
      "seleteBloodType":"रक्त प्रकार का चयन करें",
      "hospitalName":"अस्पताल का नाम",
      "RequireDate":"रक्त की आवश्यकता की तारीख",
      "bloodDonation":"रक्तदान",
      "bloodRequest" : "रक्त अनुरोध",
      "home":"घर",
      "donateBlood":"रक्तदान करें",
      "requestBlood":"रक्त का अनुरोध करें",
      "bloodDonationHistory":"रक्तदान इतिहास",
      "latest" : "नवीनतम",
      "history" : "इतिहास",
      "myList" : "मेरी सूची",
      "active":"सक्रिय",
      "adminHistory":"प्रशासन इतिहास",
      "applyFilter":'फिल्टर लागू करें',
      "cancel":'रद्द करें',
      "confirm": " पुष्टि करें",
      "clear":"साफ़ करें",
      "enterHospitalName":"यहां अस्पताल का नाम दर्ज करें",
      "bloodBankName" : "ब्लड बैंक का नाम",
      "enterBloodBankName":"यहां ब्लड बैंक का नाम दर्ज करें",
      "bloodDonationDate" : 'रक्त दान दिनांक',
      "logout":"लॉग आउट",
      "profile":"प्रोफ़ाइल",
      "changeLanguage":"भाषा बदलें",
      "changePassword":"पासवर्ड बदलें",
      "about":"हमारे बारे में",
      "LOGOUT": "लॉग आउट",
      "ARE_YOU_SURE_TO_LOGOUT": "क्या आप वाकई लॉग आउट करना चाहते हैं?",
      "CANCEL": "रद्द करें",
      "OK": "ठीक है",
      "fullName" : "पूरा नाम",
      "email" :"ईमेल",
      "DOB":"जन्म की तारीख",
      "edit":"संपादन करना",
      "editProfile":"प्रोफ़ाइल संपादित करें",
      "firstName":"पहला नाम",
      "lastName":"उपनाम",
      "update":"अद्यतन",
      "details":"विवरण",
      "bloodBankDetails":"ब्लड बैंक विवरण",
      "personalDetails":"व्यक्तिगत विवरण",
      "uploadImageWhileDonating" : "दान करते समय छवि अपलोड करें",
      "cancelRequest" : "अनुरोध को रद्द करें",
      "location" :"जगह",
      "accept":"स्वीकार करें",
      "done":"हो गया",
      "allocate":"का आवंटन",
      "Re-Allocate":"पुन: आवंटित",
      "beneficiary":"लाभार्थी",
      "Father/Husband":"पिता/पति",
      "units":"इकाइयों",
      "donor":"दाता"


      
      










    }
}
